### ISSUE TITLE
Display storage stats in Troubleshooting

### ISSUE THREAD

**Issue by manderso7** [UbuntuBudgie/budgie-welcome#224]
![Screenshot from 2019-05-16 06-01-09](https://user-images.githubusercontent.com/9535390/57845484-19a18800-77a0-11e9-85e9-24e031272122.png)
I don't see any stats when looking at the Storage section, just the names of the sections. I'm not sure if I'm missing some software that should be displaying this data or what.

**Comment by fossfreedom** [comment]
Can you please run the following in a terminal and navigate to that area.  what is reported in the terminal?

    budgie-welcome

**Comment by manderso7** [comment]
`manderso@boop:/usr$ budgie-welcome
error: no matching snaps installed
error: no matching snaps installed
error: no matching snaps installed
error: no matching snaps installed
error: no matching snaps installed
error: no matching snaps installed
error: no matching snaps installed
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/snap/ubuntu-budgie-welcome/122/usr/bin/budgie-welcome", line 254, in checkInstallationStatus
    installed = pm.hasInstalled(current_page, code)
  File "/snap/ubuntu-budgie-welcome/122/usr/bin/budgie-welcome", line 794, in hasInstalled
    ppa = repos[systemstate.codename][0][4:].split('/')
KeyError: 'bionic'

error: no matching snaps installed
error: no matching snaps installed
error: no matching snaps installed
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/snap/ubuntu-budgie-welcome/122/usr/bin/budgie-welcome", line 254, in checkInstallationStatus
    installed = pm.hasInstalled(current_page, code)
  File "/snap/ubuntu-budgie-welcome/122/usr/bin/budgie-welcome", line 794, in hasInstalled
    ppa = repos[systemstate.codename][0][4:].split('/')
KeyError: 'bionic'

[Specs] Gathering system specifications... 
list index out of range
[Specs] Failed to gather data: Storage 
`

**Comment by fossfreedom** [comment]
ok - thanks.  Can reproduce.  Will throw a fix soonest which will resolve in the next day or so.

**Comment by fossfreedom** [comment]
Should now be fixed in v0.8.5 of budgie-welcome that has been rolled out to all supported versions of UB

**Comment by manderso7** [comment]
Sorry, this still isn't working:
![Screenshot from 2019-05-22 21-25-22](https://user-images.githubusercontent.com/9535390/58219257-3118cd80-7cd8-11e9-824b-5034e722f5cc.png)
![Screenshot from 2019-05-22 21-26-26](https://user-images.githubusercontent.com/9535390/58219283-44c43400-7cd8-11e9-8b5d-ad0f65a2ceec.png)

**Comment by fossfreedom** [comment]
Hmm... ok so you have a very different issue which I cannot reproduce :(

Will need to work with you to run some test python based scripts to narrow this down.

**Comment by fossfreedom** [comment]
Ah. Wait. In your git clone version, can you run the app in a terminal to see if there is anymore info reported

     ./budgie-welcome -d

**Comment by manderso7** [comment]
Same issue, and no additional output I'm afraid.

**Comment by fossfreedom** [comment]
Please copy & paste into a new text file called "storage.py" and save to a folder

In your terminal navigate to that folder and execute the file 

    python3 storage.py

What is the output?

```
import subprocess
import os

gb_prefix = "GB"
gib_prefix = "GiB"
mb_prefix = "MB"
mib_prefix = "MiB"

def run_external_command(command, with_shell=False):
    if with_shell:
        raw = str(subprocess.Popen(command, stdout=subprocess.PIPE, shell=True).communicate()[0])
    else:
        raw = str(subprocess.Popen(command, stdout=subprocess.PIPE).communicate()[0])
    output = raw.replace("b'", "").replace('b"', "").replace("\\n'", "").replace("\\n", "")
    return output


## Gather entire disk data
root_partition = run_external_command(['mount | grep "on / "'], True).split(' ')[0]
if root_partition[:-2] == "/dev/sd":  # /dev/sdXY
    root_dev = root_partition[:-1]
if root_partition[:-2] == "/dev/hd":  # /dev/hdXY
    root_dev = root_partition[:-1]
if root_partition[:-3] == "/dev/mmcblk":  # /dev/mmcblkXpY
    root_dev = root_partition[:-2]
else:
    root_dev = root_partition[:-1]  # Generic
disk_dev_name = root_dev.split('/')[2]
print('Specs', 'Distribution is installed on disk: ' + root_dev, 1, 4)
rootfs = os.statvfs('/')
root_size = rootfs.f_blocks * rootfs.f_frsize
root_free = rootfs.f_bavail * rootfs.f_frsize
root_used = root_size - root_free
entire_disk = run_external_command(['lsblk -b | grep "' + disk_dev_name + '" | grep "disk"'], True)
entire_disk = int(entire_disk.split()[3])

## Perform calculations across units
capacity_GB = round(entire_disk / 1000 / 1000 / 1000, 1)
capacity_GiB = round(entire_disk / 1024 / 1024 / 1024, 1)
allocated_GB = round(root_size / 1000 / 1000 / 1000, 1)
allocated_GiB = round(root_size / 1024 / 1024 / 1024, 1)
used_GB = round(root_used / 1000 / 1000 / 1000, 1)
used_GiB = round(root_used / 1024 / 1024 / 1024, 1)
free_GB = round(root_free / 1000 / 1000 / 1000, 1)
free_GiB = round(root_free / 1024 / 1024 / 1024, 1)
other_GB = round((entire_disk - root_size) / 1000 / 1000 / 1000, 1)
other_GiB = round((entire_disk - root_size) / 1024 / 1024 / 1024, 1)

# Show megabytes/mebibytes (in red) if gigabytes are too small.
if capacity_GB <= 1:
    capacity_GB = str(round(entire_disk / 1000 / 1000, 1)) + ' ' + mb_prefix
    capacity_GiB = str(round(entire_disk / 1024 / 1024, 1)) + ' ' + mib_prefix
else:
    capacity_GB = str(capacity_GB) + ' ' + gb_prefix
    capacity_GiB = str(capacity_GiB) + ' ' + gib_prefix

if allocated_GB <= 1:
    allocated_GB = str(round(root_size / 1000 / 1000, 1)) + ' ' + mb_prefix
    allocated_GiB = str(round(root_size / 1024 / 1024, 1)) + ' ' + mib_prefix
else:
    allocated_GB = str(allocated_GB) + ' ' + gb_prefix
    allocated_GiB = str(allocated_GiB) + ' ' + gib_prefix

if used_GB <= 1:
    used_GB = str(round(root_used / 1000 / 1000, 1)) + ' ' + mb_prefix
    used_GiB = str(round(root_used / 1024 / 1024, 1)) + ' ' + mib_prefix
else:
    used_GB = str(used_GB) + ' ' + gb_prefix
    used_GiB = str(used_GiB) + ' ' + gib_prefix

if free_GB <= 1:
    free_GB = str(round(root_free / 1000 / 1000, 1)) + ' ' + mb_prefix
    free_GiB = str(round(root_free / 1024 / 1024, 1)) + ' ' + mib_prefix
else:
    free_GB = str(free_GB) + ' ' + gb_prefix
    free_GiB = str(free_GiB) + ' ' + gib_prefix

if other_GB <= 1:
    other_GB = str(round((entire_disk - root_size) / 1000 / 1000, 1)) + ' ' + mb_prefix
    other_GiB = str(round((entire_disk - root_size) / 1024 / 1024, 1)) + ' ' + mib_prefix
else:
    other_GB = str(other_GB) + ' ' + gb_prefix
    other_GiB = str(other_GiB) + ' ' + gib_prefix


## Calculate representation across physical disk
disk_percent_UM_used = int(round(root_used / entire_disk * 100)) * 2
disk_percent_UM_free = int(round(root_free / entire_disk * 100)) * 2
disk_percent_other = (200 - disk_percent_UM_used - disk_percent_UM_free)

# Calculate representation across physical disk
disk_percent_UM_used = int(
    round(root_used / entire_disk * 100)) * 2
disk_percent_UM_free = int(
    round(root_free / entire_disk * 100)) * 2
disk_percent_other = (
    200 - disk_percent_UM_used - disk_percent_UM_free)
print('Specs', ' Disk: ' + root_dev, 1, 4)
print('Specs',
            '  -- OS Used: ' + str(root_used) + ' bytes (' + str(disk_percent_UM_used / 2) + '%)', 1, 4)
print('Specs',
            '  -- OS Free: ' + str(root_free) + ' bytes (' + str(disk_percent_UM_free / 2) + '%)', 1, 4)
print('Specs', '  -- Other Partitions: ' + str(entire_disk - root_size) + ' bytes (' + str(
    disk_percent_other / 2) + '%)', 1, 4)
```

**Comment by manderso7** [comment]
```
➜ python3 storage.py -d
Specs Distribution is installed on disk: /dev/nvme0n1p 1 4
Traceback (most recent call last):
  File "storage.py", line 35, in <module>
    entire_disk = int(entire_disk.split()[3])
IndexError: list index out of range

```

**Comment by fossfreedom** [comment]
That's rather interesting. You appear to be running on a disk type that the code doesnt know about. 

What is the output of the following?

    lsblk -b

**Comment by manderso7** [comment]
```
➜ lsblk -b       
NAME            MAJ:MIN RM          SIZE RO TYPE MOUNTPOINT
loop0             7:0    0      17428480  1 loop /snap/ubuntu-budgie-welcome/124
loop1             7:1    0      93720576  1 loop /snap/core/6818
loop2             7:2    0     121323520  1 loop /snap/insomnia/29
loop3             7:3    0      93581312  1 loop /snap/core/6673
loop4             7:4    0     133169152  1 loop /snap/code/7
loop5             7:5    0     133107712  1 loop /snap/code/5
loop6             7:6    0      17420288  1 loop /snap/ubuntu-budgie-welcome/120
loop7             7:7    0     120815616  1 loop /snap/insomnia/28
loop8             7:8    0      17424384  1 loop /snap/ubuntu-budgie-welcome/122
loop9             7:9    0     133103616  1 loop /snap/code/6
loop11            7:11   0      92733440  1 loop /snap/core/6964
sda               8:0    0  256060514304  0 disk 
└─sda1            8:1    0  256059113472  0 part 
  └─boop--lvm-lv1
                253:1    0  756161708032  0 lvm  /mnt/lv1
sdb               8:16   0 2000398934016  0 disk 
└─sdb1            8:17   0 2000397795328  0 part 
  └─butank-butank--lvm
                253:0    0 4000787202048  0 lvm  /mnt/butank
sdc               8:32   0  500107862016  0 disk 
└─boop--lvm-lv1 253:1    0  756161708032  0 lvm  /mnt/lv1
sdd               8:48   0 2000398934016  0 disk 
└─sdd1            8:49   0 2000397868544  0 part 
  └─butank-butank--lvm
                253:0    0 4000787202048  0 lvm  /mnt/butank
sde               8:64   0 1000170586112  0 disk 
└─sde1            8:65   0 1000168488960  0 part 
nvme0n1         259:0    0  128035676160  0 disk 
├─nvme0n1p1     259:1    0     536870912  0 part /boot/efi
└─nvme0n1p2     259:2    0  127497404416  0 part /
```

**Comment by fossfreedom** [comment]
ok  - looks ok - what is the output of:

    mount | grep "on / "

**Comment by manderso7** [comment]
```
➜ mount | grep "on /"
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=16383588k,nr_inodes=4095897,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=3290076k,mode=755)
/dev/nvme0n1p2 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=1627)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
/var/lib/snapd/snaps/ubuntu-budgie-welcome_124.snap on /snap/ubuntu-budgie-welcome/124 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/core_6818.snap on /snap/core/6818 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/insomnia_29.snap on /snap/insomnia/29 type squashfs (ro,nodev,relatime,x-gdu.hide)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/var/lib/snapd/snaps/core_6673.snap on /snap/core/6673 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/code_7.snap on /snap/code/7 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/code_5.snap on /snap/code/5 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/ubuntu-budgie-welcome_120.snap on /snap/ubuntu-budgie-welcome/120 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/insomnia_28.snap on /snap/insomnia/28 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/ubuntu-budgie-welcome_122.snap on /snap/ubuntu-budgie-welcome/122 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/code_6.snap on /snap/code/6 type squashfs (ro,nodev,relatime,x-gdu.hide)
/dev/mapper/boop--lvm-lv1 on /mnt/lv1 type ext4 (rw,relatime)
/dev/mapper/butank-butank--lvm on /mnt/butank type ext4 (rw,relatime)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
//poweredge/downloads on /mnt/zfs1download type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//poweredge/movies on /mnt/zfs1movies type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//poweredge/tv on /mnt/zfs1tv type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//poweredge/music on /mnt/zfs1music type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//poweredge/dump on /mnt/zfs1dump type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3290072k,mode=700,uid=1000,gid=1000)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/fuse on /run/user/1000/doc type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/var/lib/snapd/snaps/core_6964.snap on /snap/core/6964 type squashfs (ro,nodev,relatime,x-gdu.hide)
```
```
➜ mount              
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=16383588k,nr_inodes=4095897,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=3290076k,mode=755)
/dev/nvme0n1p2 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=1627)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
/var/lib/snapd/snaps/ubuntu-budgie-welcome_124.snap on /snap/ubuntu-budgie-welcome/124 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/core_6818.snap on /snap/core/6818 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/insomnia_29.snap on /snap/insomnia/29 type squashfs (ro,nodev,relatime,x-gdu.hide)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/var/lib/snapd/snaps/core_6673.snap on /snap/core/6673 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/code_7.snap on /snap/code/7 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/code_5.snap on /snap/code/5 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/ubuntu-budgie-welcome_120.snap on /snap/ubuntu-budgie-welcome/120 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/insomnia_28.snap on /snap/insomnia/28 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/ubuntu-budgie-welcome_122.snap on /snap/ubuntu-budgie-welcome/122 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/code_6.snap on /snap/code/6 type squashfs (ro,nodev,relatime,x-gdu.hide)
/dev/mapper/boop--lvm-lv1 on /mnt/lv1 type ext4 (rw,relatime)
/dev/mapper/butank-butank--lvm on /mnt/butank type ext4 (rw,relatime)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
//poweredge/downloads on /mnt/zfs1download type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//poweredge/movies on /mnt/zfs1movies type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//poweredge/tv on /mnt/zfs1tv type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//poweredge/music on /mnt/zfs1music type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
//poweredge/dump on /mnt/zfs1dump type cifs (rw,relatime,vers=2.1,cache=strict,username=manderso,domain=,uid=1000,forceuid,gid=0,noforcegid,addr=10.0.2.14,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3290072k,mode=700,uid=1000,gid=1000)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/fuse on /run/user/1000/doc type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/var/lib/snapd/snaps/core_6964.snap on /snap/core/6964 type squashfs (ro,nodev,relatime,x-gdu.hide)
```

**Comment by fossfreedom** [comment]
very interesting!

so your install is on /dev/nvme0n1p2 but it for nvme disks that is very odd partition not a standard partition - your actual disk is nvme0n1  i.e. without the "p2".

Hence the current code can't cope with this odd naming convention. Need some magical thoughts here on how to resolve :)

**Comment by manderso7** [comment]
Thanks for looking. No idea why it's that partition structure.
